config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :events do
    resources :details
  end
  
  devise_for :users
  root "pages#index"

  namespace :api do
    namespace :v1 do
      resources :songs, only: [:index]
      resources :events, only: [:index]
    end
  end

  get '*path', controller: 'application', action: 'render_404'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :event_category
  has_many :details, dependent: :destroy
end

app/controllers/api/v1/events_controller.rb
module Api
  module V1
    class EventsController < ApplicationController

      def index
        events = EventSerializer.new(Event.all).serializable_hash
        event_data = {}
        details_data = []

        events[:data].each do |d|
          event_data['id'] = d[:id]
          event_data['by'] = d[:attributes][:by]
          details = d[:attributes][:details].to_hash

          details[:data].each do |detail|
            data = {}
            data['id'] = detail[:attributes][:id]
            data['category'] = EventCategory.find_by_id(d[:relationships][:event_category][:data][:id]).title
            data['title'] = detail[:attributes][:title]
            selected_songs_data = []

            selected = detail[:relationships][:selected_song].to_hash
            selected[:data].each do |sel|
              data_sel = {}
              data_sel['id'] = sel[:id]

              # Query DB
              selected_song = SelectedSong.find_by_id(sel[:id])
              data_sel['song_id'] = selected_song.song.id
              data_sel['title'] = selected_song.song.title
              data_sel['artist'] = selected_song.song.artist
              data_sel['lyrics_and_chords'] = selected_song.song.lyrics_and_chords

              selected_songs_data << data_sel

            end

            data['selected_songs'] = selected_songs_data
            details_data << data

            event_data['details'] = details_data
          end
        end

        render json: event_data
      end

    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @events = Event.all
  end

  def show
    @event_details = @event.details.all
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:by, :user_id, :event_category_id)
    end
end

app/views/events/_form.html.erb
<div class="card z-depth-0">
  <div class="card-content">
    <%= form_with(model: event, local: true) do |form| %>
      <%= form.hidden_field :user_id, value: current_user.id %>

      <div class="input-field">
        <p>Event Category</p>
        <%= form.collection_select(:event_category_id, EventCategory.all, :id, :title) %>
      </div>

      <div class="input-field">
        <p>By</p>
        <%= form.text_field :by, class: "form__input", placeholder: '(Ex: Guadalupe Chapter - SFC)', required: true %>
      </div>

      <div class="actions">
        <%= form.submit "Save", class: "btn z-depth-0 btn-block"%>
      </div>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<%= link_to events_path, class: "chip blue white-text u-back" do %>
  <%= material_icon.chevron_left %> Back to Events
<% end %>
<%= render 'form', event: @event %>

app/views/events/index.html.erb
<div class="row">
  <% @events.each do |event| %>
    <div class="col s12 m12 l4">
      <%= render partial: "common/event-content", locals: { event: event } %>
    </div>
  <% end %>
</div>

<% if current_user %>
  <div class="fixed-action-btn">
    <%= link_to new_event_path, class: "btn-floating btn-large blue" do %>
      <%= material_icon.add %>
    <% end %>
  </div>
<% end %>

app/views/events/new.html.erb
<%= link_to events_path, class: "chip blue white-text u-back" do %>
  <%= material_icon.chevron_left %> Back to Events
<% end %>
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<%= link_to events_path, class: "chip blue white-text u-back" do %>
  <%= material_icon.chevron_left %> Back to Events
<% end %>

<div class="row">
  <div class="col s12 m12 l4">
    <%= render partial: "common/event-content", locals: { event: @event } %>
  </div>
  <div class="col s12 m12 l8">
    <% if @event_details.size > 0 %>
      <ul class="collection event-list">
        <% @event_details.each do |detail| %>
          <li class="collection-item event-item">
            <%= link_to event_detail_path(@event, detail), class: "event-item-content event-item-title black-text" do %>
              <%= detail.title %>
            <% end %>
            <% if current_user %>
              <div class="event-item-content event-item-actions">
                <% if current_user && @event.user.id == current_user.id || current_user && current_user.admin? %>
                  <%= link_to "Edit", edit_event_detail_path(@event, detail) %>
                  <%= link_to "Remove", [@event, detail], method: :delete, data: { confirm: "Are you sure?" } %>
                <% end %>
              </div>
            <% else %>
              <div class="event-item-content event-item-actions u-next">
                <%= link_to event_detail_path(@event, detail), class: "chip blue white-text" do %>
                  <%= material_icon.chevron_right %> Open
                <% end %>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p class="center light">No Content Yet.</p>
    <% end %>

    <% if current_user && @event.user.id == current_user.id || current_user && current_user.admin? %>
      <div class="u-next">
        <%= link_to new_event_detail_path(@event), class: "chip blue white-text" do %>
          <%= material_icon.chevron_right %> Add Detail
        <% end %>
      </div>
    <% end %>
  </div>
</div>