config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :events do
    resources :details
  end
  
  devise_for :users
  root "pages#index"

  namespace :api do
    namespace :v1 do
      resources :songs, only: [:index]
      resources :events, only: [:index]
    end
  end

  get '*path', controller: 'application', action: 'render_404'
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  has_many :selected_songs, dependent: :destroy

  extend FriendlyId
  friendly_id :title, use: :slugged

  def self.search(search)
    search.nil? ? self.all : self.where("lower(title) LIKE '%#{search}%'")
  end
end

app/controllers/api/v1/songs_controller.rb
module Api
  module V1
    class SongsController < ApplicationController

      def index
        render json: SongSerializer.new(Song.all)
      end

    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:search]
      @songs = Song.search(params[:search])
    else
      @songs = Song.all.order(:title)
    end
  end

  def show
  end

  def new
    @song = Song.new
  end

  def edit
  end

  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_song
      @song = Song.friendly.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:user_id, :title, :artist, :lyrics_and_chords, :search)
    end
end

app/views/songs/_form.html.erb
<div class="card z-depth-0">
  <div class="card-content">
    <%= form_with(model: song, local: true, html: { class: "" }) do |form| %>
      <%= form.hidden_field :user_id, value: current_user.id %>

      <div class="input-field">
        <p>Title</p>
        <%= form.text_field :title, class: "form__input", placeholder: "Mission Ready", required: true %>
      </div>

      <div class="input-field">
        <p>Artist</p>
        <%= form.text_field :artist, class: "form__input", placeholder: "Liveloud", required: true %>
      </div>

      <div class="input-field">
        <p>Lyrics and Chords</p>
        <%= form.text_area :lyrics_and_chords, class: "tinymce" %>
      </div>

      <div class="actions">
        <%= form.submit "Save", class: "btn blue z-depth-0 btn-block" %>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  document.addEventListener("turbolinks:load", function() {
    tinyMCE.init({
      selector: '.tinymce',
      height: 500,
      menubar: false,
      plugins: 'code',
       toolbar: 'undo redo | formatselect | ' +
       ' forecolor | alignleft aligncenter ' +
       ' alignright alignjustify'
    });
  });
</script>

app/views/songs/_song-content.html.erb
<% @detail_songs.each do |detail_song| %>
  <div class="song-content card z-depth-0" id="<%= anchor_text(detail_song.song.title) %>">
    <div class="card-content">
      <span class="card-title"><strong><%= detail_song.song.title %></strong></span>
      <p class="grey-text"><%= detail_song.song.artist %></p>
      <div class="display-song">
        <%= raw detail_song.song.lyrics_and_chords %>
      </div>
    </div>
  </div>
<% end %>

app/views/songs/edit.html.erb
<%= link_to songs_path, class: "chip blue white-text u-back" do %>
  <%= material_icon.chevron_left %> Back to Events
<% end %>
<%= render 'form', song: @song %>

app/views/songs/index.html.erb
<div class="songs">
  <% if params[:search] %>
    <%= render "common/song-search" %>
  <% end %>

  <% if @songs %>
    <div class="songs-list">
      <% @songs.each do |song| %>
        <%= link_to song, class: "songs-item white" do %>
          <div class="songs-item__content black-text">
            <div class="songs-item__content-color js-color"></div>
            <p class="songs-item__content-title black-text"><%= song.title %></p>
            <p class="songs-item__content-editor grey-text"><%= song.artist %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/songs/new.html.erb
<%= link_to songs_path, class: "chip blue white-text u-back" do %>
  <%= material_icon.chevron_left %> Back to Events
<% end %>
<%= render 'form', song: @song %>

app/views/songs/show.html.erb
<div class="song-wrapper">
  <%= link_to songs_path, class: "chip blue white-text u-back" do %>
    <%= material_icon.chevron_left %> Back to Songs
  <% end %>

  <% if current_user && current_user.admin? %>
    <%= link_to edit_song_path(@song), class: "chip" do %>
      Edit
    <% end %>
  <% end %>

  <div class="card z-depth-0">
    <div class="song-content card-content">
      <div class="song-content song-content__title">
        <%= @song.title %>
      </div>

      <div class="song-content song-content__artist grey-text">
        By: <%= @song.artist %>
      </div>

      <div class="song-content song-content__lyrics-and-chords">
        <div class="lyrics-and-chords">
          <%= raw @song.lyrics_and_chords %>
        </div>
      </div>
    </div>
  </div>
</div>