config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :events do
    resources :details
  end
  
  devise_for :users
  root "pages#index"

  namespace :api do
    namespace :v1 do
      resources :songs, only: [:index]
      resources :events, only: [:index]
    end
  end

  get '*path', controller: 'application', action: 'render_404'
end

app/views/common/_event-content.html.erb
<%= link_to event, class: "black-text" do %>
  <div class="card z-depth-0 event-detail">
    <div class="card-content">
      <span class="card-title event-detail-text event-detail-text-title <%= event.event_category.title.downcase %>"><%= event.event_category.title %> Events</span>
      <p class="light grey-text">By: <%= event.by %></p>
    </div>
  </div>
<% end %>

app/views/common/_footer.html.erb
<footer class="page-footer grey lighten-5 center">
  <div class="footer-copyright grey lighten-5 black-text">
    <div class="container grey-text">
      Developed and Maintained with <span class="red-text">♥</span> by
      <a href="https://www.linkedin.com/in/michaellarrubis/" target="_blank">Mikel</a>
    </div>
  </div>
</footer>

app/views/common/_navbar.html.erb
<nav class="white">
  <div class="nav-wrapper container">
    <%= link_to current_title, root_path, class: "brand-logo black-text" %>
    <a href="#" data-target="slide-out" class="sidenav-trigger blue-text"><i class="material-icons">menu</i></a>
    <ul id="nav-mobile navbar-list" class="right hide-on-med-and-down">
      <li class="navbar-item"><%= link_to "Events", events_path, class: "black-text navbar-link" %></li>
      <li class="navbar-item"><%= link_to "Songs", songs_path, class: "black-text navbar-link" %></li>
      <% if user_signed_in? %>
        <li>
          <a class="dropdown-trigger black-text navbar-link" href="#!" data-target="dropdown1">
            Settings<i class="material-icons right">arrow_drop_down</i>
          </a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

<!-- Dropdown Content -->
<ul id="dropdown1" class="navbar-dropdown dropdown-content">
  <% if current_user && current_user.admin? %>
    <li class="navbar-item"><%= link_to "Add Song", new_song_path, class: "black-text navbar-link" %></li>
  <% end %>
  <li class="navbar-item"><%= link_to "Add Event", new_event_path, class: "black-text navbar-link" %></li>
  <li class="divider"></li>
  <li class="navbar-item"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "black-text navbar-link" %></li>
</ul>
<!-- Dropdown Content -->

<!-- Side Nav on SP -->
<ul id="slide-out" class="sidenav">
  <li class="navbar-item"><%= link_to "Events", events_path, class: "black-text navbar-link" %></li>
  <li class="navbar-item"><%= link_to "Songs", songs_path, class: "black-text navbar-link" %></li>
  <li class="divider"></li>
  <% if user_signed_in? %>
    <% if current_user && current_user.admin? %>
      <li class="navbar-item"><%= link_to "Add Song", new_song_path, class: "black-text navbar-link" %></li>
    <% end %>
    <li class="navbar-item"><%= link_to "Add Event", new_event_path, class: "black-text navbar-link" %></li>
    <li class="divider"></li>
    <li class="navbar-item"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "black-text navbar-link" %></li>
  <% end %>
</ul>
<!-- Side Nav on SP -->

app/views/common/_song-search.html.erb
<div class="song-search">
  <div class="card z-depth-0">
    <div class="card-content">
      <%= form_tag(songs_path, method: :get, class: "row") do %>
        <div class="input-field col s12">
          <%= text_field_tag(:search, params[:search], class: "song-search__input form__input", placeholder: "Mission Ready") %>
        </div>
      <% end %>
    </div>
  </div>
  <% if params[:search] %>
    <span class="song-search-result-total grey-text">Results Found: <%= @songs.size %></span>
  <% end %>
</div>